name: KX86
scopeName: source.kx86
fileTypes:
  - kx86
patterns:
  - match: \b(num|array|pack|asmpack|call|asmcall|inf|edit|op|random|rect|pause)\b
    name: keyword.control.kx86

  - match: (\+\+|--|\*\*|//|\+|-|\*|/|\+\+\+|---|\*\*\*|///|>f|>i)
    name: keyword.operator.kx86

  - match: \b\d+(\.\d+)?\b
    name: constant.numeric.kx86

  - match: \[[A-Za-z_][\w]*(@\d+)?\]
    name: variable.other.kx86

  - match: //:.*
    name: comment.line.double-slash.kx86

  - begin: /:
    end: :/
    name: comment.block.kx86
